AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline template
Resources:
  PipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service:
              - "cloudformation.amazonaws.com"
              - "codepipeline.amazonaws.com"
              - "lambda.amazonaws.com"
          Action: sts:AssumeRole
      Path: "/"
  PipelineRolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "PipelineRolePolicies"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action:
            - 'iam:*'
            - 's3:*'
            - 'cloudformation:*'
            - 'elasticmapreduce:*'
            - 'states:*'
            - 'sns:*'
            - 'events:*'
            - 'cloudwatch:*'
            - 'lambda:*'
            - 'ec2:*'
          Resource: "*"
      Roles:
        - Ref: PipelineRole
  DeliveryPipeline:
    DependsOn : PipelineRolePolicies
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::Join:
          - ''
          - - 'arn:aws:iam::'
            - '871404303724'
            - ":role/"
            - Ref: PipelineRole
      ArtifactStore:
        Type: S3
        Location: 'codepipeline.test.templates'
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                S3Bucket: 'codepipeline.test.templates'
                S3ObjectKey: 'artifacts/iac.zip'
              OutputArtifacts:
                -
                  Name: my-project-BuildArtifact
              RunOrder: 1
        -
          Name: CF_Deploy
          Actions:
            -
              Name: StackDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn:
                  Fn::Join:
                    - ''
                    - - 'arn:aws:iam::'
                      - '871404303724'
                      - ":role/"
                      - Ref: PipelineRole
                StackName: my-project--testName
                TemplateConfiguration: 'my-project-BuildArtifact::template-configuration.json'
                TemplatePath: 'my-project-BuildArtifact::template-export.yml'
              OutputArtifacts: [ ]
              InputArtifacts:
                - Name: my-project-BuildArtifact
              RunOrder: 1